# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "cargo" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    target-branch: "bump-version"
    ignore:
      - dependency-name: "tokio"
        versions: [">=2.0.0"]
      - dependency-name: "tokio-stream"
        versions: [">=1.0.0"]
      - dependency-name: "async-trait"
        versions: [">=0.1.0"]
      - dependency-name: "strum*"
        versions: [">=1.0.0"]
      - dependency-name: "sysinfo"
        versions: [">=0.30.0"]
