[package]
name = "get_chunk"
version = "0.2.1"
edition = "2021"
description = "Get a chunk of a file"
repository = "https://github.com/m62624/get_chunk"
categories = ["command-line-utilities"]
license = "MIT"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.9.3"
clap = { version = "4.3.23", features = ["derive"] }

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
