[package]
name = "get_chunk"
version = "1.0.0"
edition = "2021"
description = "File iterator or stream with auto or manual chunk size selection"
categories = ["asynchronous"]
keywords = ["file", "async-io", "chunk"]
license = "MIT"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
tokio = { version = "1.26.0", features = ["rt", "fs", "io-util"] }
strum = "0.25.0"
strum_macros = "0.25.3"
sysinfo = "0.29.10"
tokio-stream = "0.1.14"

[dev-dependencies]
uuid = { version = "1.5.0", features = ["v4"] }
home = "0.5.5"
rand = "0.8.5"
sha2 = "0.10.8"

[lib]
doctest = false

[features]
# for tests
tests = ["tokio/macros", "tokio/rt-multi-thread"]
